name: Carboncircledesign
favicon: null
layout_spectrum: 0.51203
typography_spectrum: 0.86463
title: Carbon Circle Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ececeb'
    - '#c5c5c4'
    - '#393638'
    - '#88786e'
    - '#008092'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
